import Foundation

public enum ExportTarget: String, CaseIterable, Identifiable {
    case swiftUI_iOS = "SwiftUI (iOS - UIKit & SwiftUI)"
    case pureUIKit_iOS = "UIKit (iOS Native - UIColor, UIFont, CALayer)"
    case swiftUI_macOS = "SwiftUI (macOS - AppKit & SwiftUI)"
    case pureAppKit_macOS = "AppKit (macOS Native - NSColor, NSFont, CALayer)"
    case tailwind = "Tailwind CSS"
    case cssVariables = "CSS Variables"
    case jetpackCompose = "Jetpack Compose (Android)"
    case flutter = "Flutter (Dart)"
    case figmaTokensStudio = "Figma Tokens Studio (JSON)"
    case figmaVariablesPlugin = "Figma Variables Script (JS)"
    case aiAgentMarkdown = "AI Agent Prompt Doc (Claude Code / Antigravity / Codex .md)"
    case w3cJson = "W3C JSON (DTCG)"
    
    public var id: String { rawValue }
    
    public var fileExtension: String {
        switch self {
        case .swiftUI_iOS, .swiftUI_macOS, .pureUIKit_iOS, .pureAppKit_macOS: return "swift"
        case .tailwind: return "js"
        case .cssVariables: return "css"
        case .jetpackCompose: return "kt"
        case .flutter: return "dart"
        case .figmaTokensStudio: return "json"
        case .figmaVariablesPlugin: return "js"
        case .aiAgentMarkdown: return "md"
        case .w3cJson: return "json"
        }
    }
}

public class CodeExporter {
    
    public static func export(project: DesignSystemProject, target: ExportTarget) -> String {
        switch target {
        case .swiftUI_iOS:
            return exportSwiftUI_iOS(project: project)
        case .pureUIKit_iOS:
            return exportPureUIKit_iOS(project: project)
        case .swiftUI_macOS:
            return exportSwiftUI_macOS(project: project)
        case .pureAppKit_macOS:
            return exportPureAppKit_macOS(project: project)
        case .tailwind:
            return exportTailwind(project: project)
        case .cssVariables:
            return exportCSSVariables(project: project)
        case .jetpackCompose:
            return exportJetpackCompose(project: project)
        case .flutter:
            return exportFlutter(project: project)
        case .figmaTokensStudio:
            return exportFigmaTokensStudio(project: project)
        case .figmaVariablesPlugin:
            return exportFigmaVariablesScript(project: project)
        case .aiAgentMarkdown:
            return exportAIAgentMarkdown(project: project)
        case .w3cJson:
            return exportW3CJson(project: project)
        }
    }
    
    // MARK: - 1. iOS SwiftUI & UIKit Exporter
    private static func exportSwiftUI_iOS(project: DesignSystemProject) -> String {
        var code = """
        // Generated by DesignSystemMake v\(project.version) for iOS
        // Target Framework: UIKit + SwiftUI (iOS 15.0+)
        // Complete Token Set: Colors, Typography, Spacing, Border Radius, Shadows
        // Date: \(DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .none))

        import SwiftUI
        import UIKit

        // MARK: - 1. Color Tokens (UIKit & SwiftUI)
        public extension UIColor {
            struct DesignTokens {
        """
        
        let colorTokens = project.tokens.filter { $0.type == .color }
        for token in colorTokens {
            guard let val = token.colorValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            if let darkHex = val.darkHex, darkHex != val.lightHex {
                code += """

                /// \(token.displayName): \(token.description)
                public static var \(varName): UIColor {
                    UIColor { traitCollection in
                        if traitCollection.userInterfaceStyle == .dark {
                            return UIColor(hex: "\(darkHex)") ?? .systemBlue
                        } else {
                            return UIColor(hex: "\(val.lightHex)") ?? .systemBlue
                        }
                    }
                }
        """
            } else {
                code += """

                /// \(token.displayName): \(token.description)
                public static let \(varName) = UIColor(hex: "\(val.lightHex)") ?? .systemBlue
        """
            }
        }
        
        code += """

            }
        }

        public extension Color {
            struct DesignTokens {
        """
        
        for token in colorTokens {
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName)
                public static var \(varName): Color { Color(uiColor: UIColor.DesignTokens.\(varName)) }
        """
        }
        
        code += """

            }
        }

        // MARK: - 2. Typography Tokens (Font & SwiftUI TextStyle)
        public extension Font {
            struct DesignTokens {
        """
        
        let typographyTokens = project.tokens.filter { $0.type == .typography }
        for token in typographyTokens {
            guard let val = token.typographyValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            let weightSwiftUI = fontStyleWeightSwiftUI(val.fontWeight)
            code += """

                /// \(token.displayName) (\(val.fontFamily) \(Int(val.fontSize))pt \(val.fontWeight))
                public static let \(varName) = Font.custom("\(val.fontFamily)", size: \(val.fontSize)).weight(\(weightSwiftUI))
        """
        }
        
        code += """

            }
        }

        public extension UIFont {
            struct DesignTokens {
        """
        
        for token in typographyTokens {
            guard let val = token.typographyValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName)
                public static var \(varName): UIFont {
                    UIFont(name: "\(val.fontFamily)", size: \(val.fontSize)) ?? UIFont.systemFont(ofSize: \(val.fontSize))
                }
        """
        }
        
        code += """

            }
        }

        // MARK: - 3. Spacing Tokens
        public extension CGFloat {
            struct DesignTokens {
        """
        
        let spacingTokens = project.tokens.filter { $0.type == .spacing }
        for token in spacingTokens {
            guard let val = token.spacingValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName) (\(Int(val.value))px)
                public static let \(varName): CGFloat = \(val.value)
        """
        }
        
        code += """

            }
        }

        // MARK: - 4. Border Radius Tokens
        public extension CGFloat {
            struct RadiusTokens {
        """
        
        let radiusTokens = project.tokens.filter { $0.type == .radius }
        for token in radiusTokens {
            guard let val = token.radiusValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName) (\(Int(val.value))px)
                public static let \(varName): CGFloat = \(val.value)
        """
        }
        
        code += """

            }
        }

        // MARK: - 5. Shadow Tokens
        public struct ShadowToken {
            public let color: Color
            public let radius: CGFloat
            public let x: CGFloat
            public let y: CGFloat
        }

        public extension ShadowToken {
            struct DesignTokens {
        """
        
        let shadowTokens = project.tokens.filter { $0.type == .shadow }
        for token in shadowTokens {
            guard let val = token.shadowValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName) (blur: \(Int(val.blur))px, y: \(Int(val.y))px)
                public static let \(varName) = ShadowToken(
                    color: Color(hex: "\(val.colorHex)").opacity(\(val.opacity)),
                    radius: \(val.blur),
                    x: \(val.x),
                    y: \(val.y)
                )
        """
        }
        
        code += """

            }
        }

        public extension View {
            func shadowToken(_ shadow: ShadowToken) -> some View {
                self.shadow(color: shadow.color, radius: shadow.radius, x: shadow.x, y: shadow.y)
            }
        }

        // MARK: - Helper Extension
        private extension UIColor {
            convenience init?(hex: String) {
                var cleanHex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
                if cleanHex.hasPrefix("#") { cleanHex.removeFirst() }
                var int: UInt64 = 0
                guard Scanner(string: cleanHex).scanHexInt64(&int) else { return nil }
                let r, g, b: CGFloat
                switch cleanHex.count {
                case 6:
                    r = CGFloat((int >> 16) & 0xFF) / 255.0
                    g = CGFloat((int >> 8) & 0xFF) / 255.0
                    b = CGFloat(int & 0xFF) / 255.0
                default:
                    return nil
                }
                self.init(red: r, green: g, blue: b, alpha: 1.0)
            }
        }
        """
        
        return code
    }
    
    // MARK: - 2. Pure UIKit Exporter (iOS Standalone)
    private static func exportPureUIKit_iOS(project: DesignSystemProject) -> String {
        var code = """
        // Generated by DesignSystemMake v\(project.version) for iOS (Pure UIKit)
        // Target Framework: UIKit (iOS 13.0+)
        // Complete Token Set: UIColor, UIFont, Spacing, Radius, CALayer Shadow
        // Date: \(DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .none))

        import UIKit

        // MARK: - 1. Dynamic UIColor Tokens
        public extension UIColor {
            struct DesignTokens {
        """
        
        let colorTokens = project.tokens.filter { $0.type == .color }
        for token in colorTokens {
            guard let val = token.colorValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            if let darkHex = val.darkHex, darkHex != val.lightHex {
                code += """

                /// \(token.displayName): \(token.description)
                public static var \(varName): UIColor {
                    UIColor { traitCollection in
                        if traitCollection.userInterfaceStyle == .dark {
                            return UIColor(hex: "\(darkHex)") ?? .systemBlue
                        } else {
                            return UIColor(hex: "\(val.lightHex)") ?? .systemBlue
                        }
                    }
                }
        """
            } else {
                code += """

                /// \(token.displayName): \(token.description)
                public static let \(varName) = UIColor(hex: "\(val.lightHex)") ?? .systemBlue
        """
            }
        }
        
        code += """

            }
        }

        // MARK: - 2. UIFont Tokens
        public extension UIFont {
            struct DesignTokens {
        """
        
        let typographyTokens = project.tokens.filter { $0.type == .typography }
        for token in typographyTokens {
            guard let val = token.typographyValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName) (\(val.fontFamily) \(Int(val.fontSize))pt \(val.fontWeight))
                public static var \(varName): UIFont {
                    UIFont(name: "\(val.fontFamily)", size: \(val.fontSize)) ?? UIFont.systemFont(ofSize: \(val.fontSize))
                }
        """
        }
        
        code += """

            }
        }

        // MARK: - 3. Spacing Tokens
        public struct UIKitSpacingTokens {
        """
        
        let spacingTokens = project.tokens.filter { $0.type == .spacing }
        for token in spacingTokens {
            guard let val = token.spacingValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

            /// \(token.displayName) (\(Int(val.value))px)
            public static let \(varName): CGFloat = \(val.value)
        """
        }
        
        code += """

        }

        // MARK: - 4. Border Radius Tokens
        public struct UIKitRadiusTokens {
        """
        
        let radiusTokens = project.tokens.filter { $0.type == .radius }
        for token in radiusTokens {
            guard let val = token.radiusValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

            /// \(token.displayName) (\(Int(val.value))px)
            public static let \(varName): CGFloat = \(val.value)
        """
        }
        
        code += """

        }

        // MARK: - 5. CALayer Shadow Extensions
        public extension CALayer {
            func applyShadowToken(color: UIColor, x: CGFloat, y: CGFloat, blur: CGFloat, opacity: Float) {
                self.shadowColor = color.cgColor
                self.shadowOffset = CGSize(width: x, height: y)
                self.shadowRadius = blur / 2.0
                self.shadowOpacity = opacity
            }
        }

        // MARK: - Helper Extension
        private extension UIColor {
            convenience init?(hex: String) {
                var cleanHex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
                if cleanHex.hasPrefix("#") { cleanHex.removeFirst() }
                var int: UInt64 = 0
                guard Scanner(string: cleanHex).scanHexInt64(&int) else { return nil }
                let r, g, b: CGFloat
                switch cleanHex.count {
                case 6:
                    r = CGFloat((int >> 16) & 0xFF) / 255.0
                    g = CGFloat((int >> 8) & 0xFF) / 255.0
                    b = CGFloat(int & 0xFF) / 255.0
                default:
                    return nil
                }
                self.init(red: r, green: g, blue: b, alpha: 1.0)
            }
        }
        """
        
        return code
    }
    
    // MARK: - 3. macOS SwiftUI & AppKit Exporter
    private static func exportSwiftUI_macOS(project: DesignSystemProject) -> String {
        var code = """
        // Generated by DesignSystemMake v\(project.version) for macOS
        // Target Framework: AppKit + SwiftUI (macOS 12.0+)
        // Complete Token Set: Colors, Typography, Spacing, Border Radius, Shadows
        // Date: \(DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .none))

        import SwiftUI
        import AppKit

        // MARK: - 1. Color Tokens (AppKit & SwiftUI)
        public extension NSColor {
            struct DesignTokens {
        """
        
        let colorTokens = project.tokens.filter { $0.type == .color }
        for token in colorTokens {
            guard let val = token.colorValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            if let darkHex = val.darkHex, darkHex != val.lightHex {
                code += """

                /// \(token.displayName): \(token.description)
                public static var \(varName): NSColor {
                    NSColor(name: nil, dynamicProvider: { appearance in
                        if appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua {
                            return NSColor(hex: "\(darkHex)") ?? NSColor.black
                        } else {
                            return NSColor(hex: "\(val.lightHex)") ?? NSColor.white
                        }
                    })
                }
        """
            } else {
                code += """

                /// \(token.displayName): \(token.description)
                public static let \(varName) = NSColor(hex: "\(val.lightHex)") ?? NSColor.controlAccentColor
        """
            }
        }
        
        code += """

            }
        }

        public extension Color {
            struct DesignTokens {
        """
        
        for token in colorTokens {
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName)
                public static var \(varName): Color { Color(nsColor: NSColor.DesignTokens.\(varName)) }
        """
        }
        
        code += """

            }
        }

        // MARK: - 2. Typography Tokens
        public extension Font {
            struct DesignTokens {
        """
        
        let typographyTokens = project.tokens.filter { $0.type == .typography }
        for token in typographyTokens {
            guard let val = token.typographyValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            let weightSwiftUI = fontStyleWeightSwiftUI(val.fontWeight)
            code += """

                /// \(token.displayName) (\(val.fontFamily) \(Int(val.fontSize))pt \(val.fontWeight))
                public static let \(varName) = Font.custom("\(val.fontFamily)", size: \(val.fontSize)).weight(\(weightSwiftUI))
        """
        }
        
        code += """

            }
        }

        public extension NSFont {
            struct DesignTokens {
        """
        
        for token in typographyTokens {
            guard let val = token.typographyValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName)
                public static var \(varName): NSFont {
                    NSFont(name: "\(val.fontFamily)", size: \(val.fontSize)) ?? NSFont.systemFont(ofSize: \(val.fontSize))
                }
        """
        }
        
        code += """

            }
        }

        // MARK: - 3. Spacing Tokens
        public extension CGFloat {
            struct DesignTokens {
        """
        
        let spacingTokens = project.tokens.filter { $0.type == .spacing }
        for token in spacingTokens {
            guard let val = token.spacingValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName) (\(Int(val.value))px)
                public static let \(varName): CGFloat = \(val.value)
        """
        }
        
        code += """

            }
        }

        // MARK: - 4. Border Radius Tokens
        public extension CGFloat {
            struct RadiusTokens {
        """
        
        let radiusTokens = project.tokens.filter { $0.type == .radius }
        for token in radiusTokens {
            guard let val = token.radiusValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName) (\(Int(val.value))px)
                public static let \(varName): CGFloat = \(val.value)
        """
        }
        
        code += """

            }
        }

        // MARK: - 5. Shadow Tokens
        public struct ShadowToken {
            public let color: Color
            public let radius: CGFloat
            public let x: CGFloat
            public let y: CGFloat
        }

        public extension ShadowToken {
            struct DesignTokens {
        """
        
        let shadowTokens = project.tokens.filter { $0.type == .shadow }
        for token in shadowTokens {
            guard let val = token.shadowValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName) (blur: \(Int(val.blur))px, y: \(Int(val.y))px)
                public static let \(varName) = ShadowToken(
                    color: Color(hex: "\(val.colorHex)").opacity(\(val.opacity)),
                    radius: \(val.blur),
                    x: \(val.x),
                    y: \(val.y)
                )
        """
        }
        
        code += """

            }
        }

        public extension View {
            func shadowToken(_ shadow: ShadowToken) -> some View {
                self.shadow(color: shadow.color, radius: shadow.radius, x: shadow.x, y: shadow.y)
            }
        }

        // MARK: - Helper Extension
        private extension NSColor {
            convenience init?(hex: String) {
                var cleanHex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
                if cleanHex.hasPrefix("#") { cleanHex.removeFirst() }
                var int: UInt64 = 0
                guard Scanner(string: cleanHex).scanHexInt64(&int) else { return nil }
                let r, g, b: CGFloat
                switch cleanHex.count {
                case 6:
                    r = CGFloat((int >> 16) & 0xFF) / 255.0
                    g = CGFloat((int >> 8) & 0xFF) / 255.0
                    b = CGFloat(int & 0xFF) / 255.0
                default:
                    return nil
                }
                self.init(srgbRed: r, green: g, blue: b, alpha: 1.0)
            }
        }
        """
        
        return code
    }

    // MARK: - 4. Pure AppKit Exporter (macOS Standalone)
    private static func exportPureAppKit_macOS(project: DesignSystemProject) -> String {
        var code = """
        // Generated by DesignSystemMake v\(project.version) for macOS (Pure AppKit)
        // Target Framework: AppKit (macOS 10.15+)
        // Complete Token Set: NSColor, NSFont, Spacing, Radius, NSShadow
        // Date: \(DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .none))

        import AppKit

        // MARK: - 1. Dynamic NSColor Tokens
        public extension NSColor {
            struct DesignTokens {
        """
        
        let colorTokens = project.tokens.filter { $0.type == .color }
        for token in colorTokens {
            guard let val = token.colorValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            if let darkHex = val.darkHex, darkHex != val.lightHex {
                code += """

                /// \(token.displayName): \(token.description)
                public static var \(varName): NSColor {
                    NSColor(name: nil, dynamicProvider: { appearance in
                        if appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua {
                            return NSColor(hex: "\(darkHex)") ?? NSColor.black
                        } else {
                            return NSColor(hex: "\(val.lightHex)") ?? NSColor.white
                        }
                    })
                }
        """
            } else {
                code += """

                /// \(token.displayName): \(token.description)
                public static let \(varName) = NSColor(hex: "\(val.lightHex)") ?? NSColor.controlAccentColor
        """
            }
        }
        
        code += """

            }
        }

        // MARK: - 2. NSFont Tokens
        public extension NSFont {
            struct DesignTokens {
        """
        
        let typographyTokens = project.tokens.filter { $0.type == .typography }
        for token in typographyTokens {
            guard let val = token.typographyValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

                /// \(token.displayName) (\(val.fontFamily) \(Int(val.fontSize))pt \(val.fontWeight))
                public static var \(varName): NSFont {
                    NSFont(name: "\(val.fontFamily)", size: \(val.fontSize)) ?? NSFont.systemFont(ofSize: \(val.fontSize))
                }
        """
        }
        
        code += """

            }
        }

        // MARK: - 3. Spacing Tokens
        public struct AppKitSpacingTokens {
        """
        
        let spacingTokens = project.tokens.filter { $0.type == .spacing }
        for token in spacingTokens {
            guard let val = token.spacingValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

            /// \(token.displayName) (\(Int(val.value))px)
            public static let \(varName): CGFloat = \(val.value)
        """
        }
        
        code += """

        }

        // MARK: - 4. Border Radius Tokens
        public struct AppKitRadiusTokens {
        """
        
        let radiusTokens = project.tokens.filter { $0.type == .radius }
        for token in radiusTokens {
            guard let val = token.radiusValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += """

            /// \(token.displayName) (\(Int(val.value))px)
            public static let \(varName): CGFloat = \(val.value)
        """
        }
        
        code += """

        }

        // MARK: - 5. NSShadow Extensions
        public extension NSShadow {
            static func createShadowToken(color: NSColor, x: CGFloat, y: CGFloat, blur: CGFloat) -> NSShadow {
                let shadow = NSShadow()
                shadow.shadowColor = color
                shadow.shadowOffset = NSSize(width: x, height: y)
                shadow.shadowBlurRadius = blur
                return shadow
            }
        }

        // MARK: - Helper Extension
        private extension NSColor {
            convenience init?(hex: String) {
                var cleanHex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
                if cleanHex.hasPrefix("#") { cleanHex.removeFirst() }
                var int: UInt64 = 0
                guard Scanner(string: cleanHex).scanHexInt64(&int) else { return nil }
                let r, g, b: CGFloat
                switch cleanHex.count {
                case 6:
                    r = CGFloat((int >> 16) & 0xFF) / 255.0
                    g = CGFloat((int >> 8) & 0xFF) / 255.0
                    b = CGFloat(int & 0xFF) / 255.0
                default:
                    return nil
                }
                self.init(srgbRed: r, green: g, blue: b, alpha: 1.0)
            }
        }
        """
        
        return code
    }

    // MARK: - 5. Tailwind CSS Exporter
    private static func exportTailwind(project: DesignSystemProject) -> String {
        var colorsJS = "      colors: {\n"
        for token in project.tokens.filter({ $0.type == .color }) {
            guard let val = token.colorValue else { continue }
            let keyName = token.name.replacingOccurrences(of: ".", with: "-").lowercased()
            colorsJS += "        '\(keyName)': '\(val.lightHex)',\n"
        }
        colorsJS += "      },"
        
        var spacingJS = "      spacing: {\n"
        for token in project.tokens.filter({ $0.type == .spacing }) {
            guard let val = token.spacingValue else { continue }
            let keyName = token.name.replacingOccurrences(of: ".", with: "-").lowercased()
            spacingJS += "        '\(keyName)': '\(val.value)\(val.unit)',\n"
        }
        spacingJS += "      },"
        
        var radiusJS = "      borderRadius: {\n"
        for token in project.tokens.filter({ $0.type == .radius }) {
            guard let val = token.radiusValue else { continue }
            let keyName = token.name.replacingOccurrences(of: ".", with: "-").lowercased()
            radiusJS += "        '\(keyName)': '\(val.value)px',\n"
        }
        radiusJS += "      },"
        
        var fontFamilyJS = "      fontFamily: {\n"
        var fontSizeJS = "      fontSize: {\n"
        for token in project.tokens.filter({ $0.type == .typography }) {
            guard let val = token.typographyValue else { continue }
            let keyName = token.name.replacingOccurrences(of: ".", with: "-").lowercased()
            fontFamilyJS += "        '\(keyName)': ['\(val.fontFamily)', 'sans-serif'],\n"
            fontSizeJS += "        '\(keyName)': ['\(Int(val.fontSize))px', { lineHeight: '\(Int(val.lineHeight))px' }],\n"
        }
        fontFamilyJS += "      },"
        fontSizeJS += "      },"
        
        var boxShadowJS = "      boxShadow: {\n"
        for token in project.tokens.filter({ $0.type == .shadow }) {
            guard let val = token.shadowValue else { continue }
            let keyName = token.name.replacingOccurrences(of: ".", with: "-").lowercased()
            boxShadowJS += "        '\(keyName)': '\(Int(val.x))px \(Int(val.y))px \(Int(val.blur))px rgba(0,0,0,\(val.opacity))',\n"
        }
        boxShadowJS += "      },"
        
        return """
        // tailwind.config.js - Generated by DesignSystemMake v\(project.version)
        // Includes: Colors, Typography, Spacing, Border Radius, Box Shadows
        module.exports = {
          darkMode: 'class',
          theme: {
            extend: {
        \(colorsJS)
        \(spacingJS)
        \(radiusJS)
        \(fontFamilyJS)
        \(fontSizeJS)
        \(boxShadowJS)
            },
          },
          plugins: [],
        };
        """
    }
    
    // MARK: - 6. CSS Variables Exporter
    private static func exportCSSVariables(project: DesignSystemProject) -> String {
        var rootLines: [String] = []
        var darkLines: [String] = []
        
        for token in project.tokens {
            let varName = "--" + token.name.replacingOccurrences(of: ".", with: "-").lowercased()
            switch token.type {
            case .color:
                if let val = token.colorValue {
                    rootLines.append("  \(varName): \(val.lightHex);")
                    if let darkHex = val.darkHex, darkHex != val.lightHex {
                        darkLines.append("  \(varName): \(darkHex);")
                    }
                }
            case .spacing:
                if let val = token.spacingValue {
                    rootLines.append("  \(varName): \(val.value)\(val.unit);")
                }
            case .radius:
                if let val = token.radiusValue {
                    rootLines.append("  \(varName): \(val.value)px;")
                }
            case .typography:
                if let val = token.typographyValue {
                    rootLines.append("  \(varName)-family: '\(val.fontFamily)', sans-serif;")
                    rootLines.append("  \(varName)-size: \(Int(val.fontSize))px;")
                    rootLines.append("  \(varName)-weight: \(fontWeightCssNumber(val.fontWeight));")
                    rootLines.append("  \(varName)-line-height: \(Int(val.lineHeight))px;")
                }
            case .shadow:
                if let val = token.shadowValue {
                    rootLines.append("  \(varName): \(Int(val.x))px \(Int(val.y))px \(Int(val.blur))px rgba(0, 0, 0, \(val.opacity));")
                }
            }
        }
        
        var css = "/* Generated by DesignSystemMake v\(project.version) */\n/* Complete Tokens: Colors, Typography, Spacing, Radius, Shadows */\n:root {\n"
        css += rootLines.joined(separator: "\n")
        css += "\n}\n\n"
        if !darkLines.isEmpty {
            css += "[data-theme=\"dark\"], .dark {\n"
            css += darkLines.joined(separator: "\n")
            css += "\n}\n"
        }
        return css
    }
    
    // MARK: - 7. Jetpack Compose Exporter
    private static func exportJetpackCompose(project: DesignSystemProject) -> String {
        var code = """
        // Generated by DesignSystemMake v\(project.version) for Android Compose
        // Includes: Colors, Typography, Spacing, Shapes/Radius, Shadows
        package com.example.designsystem.ui.theme

        import androidx.compose.ui.graphics.Color
        import androidx.compose.ui.graphics.Shadow
        import androidx.compose.ui.geometry.Offset
        import androidx.compose.ui.unit.dp
        import androidx.compose.ui.unit.sp
        import androidx.compose.ui.text.TextStyle
        import androidx.compose.ui.text.font.FontFamily
        import androidx.compose.ui.text.font.FontWeight
        import androidx.compose.foundation.shape.RoundedCornerShape

        object AppDesignTokens {
            // 1. Color Tokens
        """
        
        for token in project.tokens.filter({ $0.type == .color }) {
            guard let val = token.colorValue else { continue }
            let varName = sanitizeIdentifier(token.name).capitalized
            let hexClean = val.lightHex.replacingOccurrences(of: "#", with: "")
            code += "\n    val Color\(varName) = Color(0xFF\(hexClean.uppercased()))"
        }
        
        code += "\n\n    // 2. Spacing Tokens"
        for token in project.tokens.filter({ $0.type == .spacing }) {
            guard let val = token.spacingValue else { continue }
            let varName = sanitizeIdentifier(token.name).capitalized
            code += "\n    val Spacing\(varName) = \(Int(val.value)).dp"
        }
        
        code += "\n\n    // 3. Border Radius / Shape Tokens"
        for token in project.tokens.filter({ $0.type == .radius }) {
            guard let val = token.radiusValue else { continue }
            let varName = sanitizeIdentifier(token.name).capitalized
            code += "\n    val Radius\(varName) = RoundedCornerShape(\(Int(val.value)).dp)"
        }
        
        code += "\n\n    // 4. Typography Tokens"
        for token in project.tokens.filter({ $0.type == .typography }) {
            guard let val = token.typographyValue else { continue }
            let varName = sanitizeIdentifier(token.name).capitalized
            let weightKotlin = fontWeightKotlinCompose(val.fontWeight)
            code += """

                val Typography\(varName) = TextStyle(
                    fontFamily = FontFamily.Default,
                    fontSize = \(Int(val.fontSize)).sp,
                    fontWeight = \(weightKotlin)
                )
            """
        }
        
        code += "\n\n    // 5. Shadow Tokens"
        for token in project.tokens.filter({ $0.type == .shadow }) {
            guard let val = token.shadowValue else { continue }
            let varName = sanitizeIdentifier(token.name).capitalized
            let hexClean = val.colorHex.replacingOccurrences(of: "#", with: "")
            code += """

                val Shadow\(varName) = Shadow(
                    color = Color(0xFF\(hexClean.uppercased())),
                    offset = Offset(\(val.x)f, \(val.y)f),
                    blurRadius = \(val.blur)f
                )
            """
        }
        
        code += "\n}\n"
        return code
    }
    
    // MARK: - 8. Flutter Exporter
    private static func exportFlutter(project: DesignSystemProject) -> String {
        var code = """
        // Generated by DesignSystemMake v\(project.version) for Flutter (Dart)
        // Includes: Colors, Typography, Spacing, Border Radius, Box Shadows
        import 'package:flutter/material.dart';

        class AppDesignTokens {
          AppDesignTokens._();

          // 1. Colors
        """
        
        for token in project.tokens.filter({ $0.type == .color }) {
            guard let val = token.colorValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            let hexClean = val.lightHex.replacingOccurrences(of: "#", with: "")
            code += "\n  static const Color \(varName) = Color(0xFF\(hexClean.uppercased()));"
        }
        
        code += "\n\n  // 2. Spacing"
        for token in project.tokens.filter({ $0.type == .spacing }) {
            guard let val = token.spacingValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += "\n  static const double spacing\(varName.capitalized) = \(val.value);"
        }
        
        code += "\n\n  // 3. Border Radius"
        for token in project.tokens.filter({ $0.type == .radius }) {
            guard let val = token.radiusValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            code += "\n  static const BorderRadius radius\(varName.capitalized) = BorderRadius.all(Radius.circular(\(val.value)));"
        }
        
        code += "\n\n  // 4. Typography"
        for token in project.tokens.filter({ $0.type == .typography }) {
            guard let val = token.typographyValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            let weightDart = fontWeightFlutterDart(val.fontWeight)
            code += """

              static const TextStyle typography\(varName.capitalized) = TextStyle(
                fontFamily: '\(val.fontFamily)',
                fontSize: \(val.fontSize),
                fontWeight: \(weightDart),
              );
            """
        }
        
        code += "\n\n  // 5. Box Shadows"
        for token in project.tokens.filter({ $0.type == .shadow }) {
            guard let val = token.shadowValue else { continue }
            let varName = sanitizeIdentifier(token.name)
            let hexClean = val.colorHex.replacingOccurrences(of: "#", with: "")
            let opacityHex = String(format: "%02X", Int(val.opacity * 255))
            code += """

              static const BoxShadow shadow\(varName.capitalized) = BoxShadow(
                color: Color(0x\(opacityHex)\(hexClean.uppercased())),
                offset: Offset(\(val.x), \(val.y)),
                blurRadius: \(val.blur),
              );
            """
        }
        
        code += "\n}\n"
        return code
    }
    
    // MARK: - 9. AI Agent Prompt Documentation Exporter (.md)
    private static func exportAIAgentMarkdown(project: DesignSystemProject) -> String {
        var md = """
        # 🤖 Design System Rules & Tokens: \(project.name)
        > **System Prompt Context for AI Coding Agents (Claude Code, Antigravity CLI, OpenAI Codex, Cursor)**
        > Project Version: \(project.version) | Generated by DesignSystemMake
        > 
        > **CRITICAL INSTRUCTIONS FOR AI AGENTS**:
        > When writing, refactoring, or generating UI code for this repository, you MUST strictly use the design system tokens documented below. 
        > DO NOT hardcode raw hex colors, arbitrary pixel paddings, or non-standard font sizes!

        ---

        ## 🎨 1. Color Tokens
        | Token Key | Light Mode Hex | Dark Mode Hex | Description | WCAG 2.1 Ratio |
        | :--- | :--- | :--- | :--- | :--- |
        """
        
        for token in project.tokens.filter({ $0.type == .color }) {
            guard let val = token.colorValue else { continue }
            let darkHex = val.darkHex ?? val.lightHex
            let wcag = ContrastCalculator.evaluateContrast(foregroundHex: val.lightHex, backgroundHex: "#FFFFFF")
            md += "\n| `\(token.name)` | `\(val.lightHex)` | `\(darkHex)` | \(token.description) | \(wcag.formattedRatio) (\(wcag.passesAANormal ? "AA Pass" : "Fail")) |"
        }
        
        md += """


        ---

        ## 🔤 2. Typography Tokens
        | Token Key | Font Family | Size | Weight | Line Height | Description |
        | :--- | :--- | :--- | :--- | :--- | :--- |
        """
        
        for token in project.tokens.filter({ $0.type == .typography }) {
            guard let val = token.typographyValue else { continue }
            md += "\n| `\(token.name)` | `\(val.fontFamily)` | `\(Int(val.fontSize))pt` | `\(val.fontWeight)` | `\(Int(val.lineHeight))pt` | \(token.description) |"
        }
        
        md += """


        ---

        ## 📐 3. Spacing Tokens
        | Token Key | Value | Description |
        | :--- | :--- | :--- |
        """
        
        for token in project.tokens.filter({ $0.type == .spacing }) {
            guard let val = token.spacingValue else { continue }
            md += "\n| `\(token.name)` | `\(Int(val.value))\(val.unit)` | \(token.description) |"
        }
        
        md += """


        ---

        ## ⭕ 4. Border Radius Tokens
        | Token Key | Value | Description |
        | :--- | :--- | :--- |
        """
        
        for token in project.tokens.filter({ $0.type == .radius }) {
            guard let val = token.radiusValue else { continue }
            md += "\n| `\(token.name)` | `\(Int(val.value))px` | \(token.description) |"
        }
        
        md += """


        ---

        ## 🌫️ 5. Shadow Tokens
        | Token Key | Blur | Offset (X, Y) | Opacity | Description |
        | :--- | :--- | :--- | :--- | :--- |
        """
        
        for token in project.tokens.filter({ $0.type == .shadow }) {
            guard let val = token.shadowValue else { continue }
            md += "\n| `\(token.name)` | `\(Int(val.blur))px` | (`\(Int(val.x))`, `\(Int(val.y))`) | `\(val.opacity)` | \(token.description) |"
        }
        
        md += """


        ---

        ## 🛠️ Code Syntax Reference Cheat Sheet for AI

        ### SwiftUI Example
        ```swift
        // Apply Color Tokens
        Color.DesignTokens.brandPrimary
        
        // Apply Spacing & Radius Tokens
        .padding(CGFloat.DesignTokens.spacingMd)
        .cornerRadius(CGFloat.RadiusTokens.radiusMd)
        ```

        ### Tailwind CSS Example
        ```html
        <div class="bg-brand-primary p-spacing-md rounded-radius-md shadow-card">
          <span class="font-body-medium">Design System Managed</span>
        </div>
        ```

        ### CSS Variables Example
        ```css
        .container {
          background-color: var(--color-brand-primary);
          padding: var(--spacing-md);
          border-radius: var(--radius-md);
          box-shadow: var(--shadow-card);
        }
        ```
        """
        
        return md
    }
    
    // MARK: - 10. Figma Tokens Studio (JSON) Exporter
    private static func exportFigmaTokensStudio(project: DesignSystemProject) -> String {
        var tokensDict: [String: Any] = [:]
        
        for token in project.tokens {
            let keyPath = token.name.components(separatedBy: ".")
            var typeString = "other"
            var valueAny: Any = ""
            
            switch token.type {
            case .color:
                typeString = "color"
                if let val = token.colorValue {
                    valueAny = val.lightHex
                }
            case .spacing:
                typeString = "spacing"
                if let val = token.spacingValue {
                    valueAny = "\(val.value)px"
                }
            case .radius:
                typeString = "borderRadius"
                if let val = token.radiusValue {
                    valueAny = "\(val.value)px"
                }
            case .typography:
                typeString = "typography"
                if let val = token.typographyValue {
                    valueAny = [
                        "fontFamily": val.fontFamily,
                        "fontSize": "\(val.fontSize)px",
                        "fontWeight": val.fontWeight,
                        "lineHeight": "\(val.lineHeight)px"
                    ]
                }
            case .shadow:
                typeString = "boxShadow"
                if let val = token.shadowValue {
                    valueAny = [
                        "color": val.colorHex,
                        "x": "\(val.x)px",
                        "y": "\(val.y)px",
                        "blur": "\(val.blur)px",
                        "spread": "\(val.spread)px"
                    ]
                }
            }
            
            let tokenObj: [String: Any] = [
                "value": valueAny,
                "type": typeString,
                "description": token.description
            ]
            
            setValue(in: &tokensDict, keyPath: keyPath, value: tokenObj)
        }
        
        let root: [String: Any] = [
            "global": tokensDict
        ]
        
        if let jsonData = try? JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys]),
           let jsonString = String(data: jsonData, encoding: .utf8) {
            return jsonString
        }
        return "{}"
    }
    
    // MARK: - 11. Figma Variables Plugin JS Script Exporter
    private static func exportFigmaVariablesScript(project: DesignSystemProject) -> String {
        var script = """
        // Figma Native Variables Auto-Importer Script
        // Generated by DesignSystemMake for \(project.name)
        // Instructions: Paste this code into Figma Plugin Console (Cmd+Option+I in Figma Desktop) to create Native Variables automatically!

        (async () => {
          console.log("🚀 Starting Figma Variables Auto-Import...");
          
          const collections = await figma.variables.getLocalVariableCollectionsAsync();
          let collection = collections.find(c => c.name === "\(project.name)");
          if (!collection) {
            collection = figma.variables.createVariableCollection("\(project.name)");
          }
          const modeId = collection.modes[0].modeId;

        """
        
        for token in project.tokens {
            let varFigmaName = token.name.replacingOccurrences(of: ".", with: "/")
            
            switch token.type {
            case .color:
                if let val = token.colorValue, let rgb = ContrastCalculator.parseHex(val.lightHex) {
                    script += """

                      // Color: \(token.displayName)
                      const var_\(sanitizeIdentifier(token.name)) = figma.variables.createVariable("\(varFigmaName)", collection.id, "COLOR");
                      var_\(sanitizeIdentifier(token.name)).setValueForMode(modeId, { r: \(rgb.r), g: \(rgb.g), b: \(rgb.b), a: \(rgb.a) });
                    """
                }
            case .spacing:
                if let val = token.spacingValue {
                    script += """

                      // Spacing: \(token.displayName)
                      const var_\(sanitizeIdentifier(token.name)) = figma.variables.createVariable("\(varFigmaName)", collection.id, "FLOAT");
                      var_\(sanitizeIdentifier(token.name)).setValueForMode(modeId, \(val.value));
                    """
                }
            case .radius:
                if let val = token.radiusValue {
                    script += """

                      // Radius: \(token.displayName)
                      const var_\(sanitizeIdentifier(token.name)) = figma.variables.createVariable("\(varFigmaName)", collection.id, "FLOAT");
                      var_\(sanitizeIdentifier(token.name)).setValueForMode(modeId, \(val.value));
                    """
                }
            case .typography:
                if let val = token.typographyValue {
                    script += """

                      // Typography Font Size: \(token.displayName)
                      const var_\(sanitizeIdentifier(token.name))_size = figma.variables.createVariable("\(varFigmaName)/fontSize", collection.id, "FLOAT");
                      var_\(sanitizeIdentifier(token.name))_size.setValueForMode(modeId, \(val.fontSize));
                      
                      // Typography Font Family: \(token.displayName)
                      const var_\(sanitizeIdentifier(token.name))_family = figma.variables.createVariable("\(varFigmaName)/fontFamily", collection.id, "STRING");
                      var_\(sanitizeIdentifier(token.name))_family.setValueForMode(modeId, "\(val.fontFamily)");
                    """
                }
            default:
                break
            }
        }
        
        script += """


          figma.notify("✅ Created Native Figma Variables for \(project.name)!");
          console.log("🎉 Successfully created Native Figma Variables!");
        })();
        """
        
        return script
    }
    
    // MARK: - 12. W3C JSON Exporter
    private static func exportW3CJson(project: DesignSystemProject) -> String {
        var dict: [String: Any] = [:]
        
        for token in project.tokens {
            let keyPath = token.name.components(separatedBy: ".")
            var subDict: [String: Any] = [
                "$description": token.description,
                "$type": token.type.rawValue.lowercased()
            ]
            
            switch token.type {
            case .color:
                if let val = token.colorValue {
                    subDict["$value"] = val.lightHex
                }
            case .spacing:
                if let val = token.spacingValue {
                    subDict["$value"] = "\(val.value)\(val.unit)"
                }
            case .radius:
                if let val = token.radiusValue {
                    subDict["$value"] = "\(val.value)px"
                }
            case .typography:
                if let val = token.typographyValue {
                    subDict["$value"] = [
                        "fontFamily": val.fontFamily,
                        "fontSize": "\(val.fontSize)px",
                        "fontWeight": val.fontWeight,
                        "lineHeight": "\(val.lineHeight)px"
                    ]
                }
            case .shadow:
                if let val = token.shadowValue {
                    subDict["$value"] = [
                        "color": val.colorHex,
                        "offsetX": "\(val.x)px",
                        "offsetY": "\(val.y)px",
                        "blur": "\(val.blur)px"
                    ]
                }
            }
            
            setValue(in: &dict, keyPath: keyPath, value: subDict)
        }
        
        if let jsonData = try? JSONSerialization.data(withJSONObject: dict, options: [.prettyPrinted, .sortedKeys]),
           let jsonString = String(data: jsonData, encoding: .utf8) {
            return jsonString
        }
        return "{}"
    }
    
    // MARK: - Helpers
    private static func fontStyleWeightSwiftUI(_ weight: String) -> String {
        switch weight.lowercased() {
        case "bold": return ".bold"
        case "semibold": return ".semibold"
        case "medium": return ".medium"
        default: return ".regular"
        }
    }
    
    private static func fontWeightCssNumber(_ weight: String) -> String {
        switch weight.lowercased() {
        case "bold": return "700"
        case "semibold": return "600"
        case "medium": return "500"
        default: return "400"
        }
    }
    
    private static func fontWeightKotlinCompose(_ weight: String) -> String {
        switch weight.lowercased() {
        case "bold": return "FontWeight.Bold"
        case "semibold": return "FontWeight.SemiBold"
        case "medium": return "FontWeight.Medium"
        default: return "FontWeight.Normal"
        }
    }
    
    private static func fontWeightFlutterDart(_ weight: String) -> String {
        switch weight.lowercased() {
        case "bold": return "FontWeight.bold"
        case "semibold": return "FontWeight.w600"
        case "medium": return "FontWeight.w500"
        default: return "FontWeight.normal"
        }
    }
    
    private static func sanitizeIdentifier(_ name: String) -> String {
        let parts = name.components(separatedBy: CharacterSet.alphanumerics.inverted)
        let camel = parts.enumerated().map { index, part in
            index == 0 ? part.lowercased() : part.capitalized
        }.joined()
        return camel.isEmpty ? "token" : camel
    }
    
    private static func setValue(in dict: inout [String: Any], keyPath: [String], value: [String: Any]) {
        guard let first = keyPath.first else { return }
        if keyPath.count == 1 {
            dict[first] = value
        } else {
            var sub = (dict[first] as? [String: Any]) ?? [:]
            setValue(in: &sub, keyPath: Array(keyPath.dropFirst()), value: value)
            dict[first] = sub
        }
    }
}
